name: cyto_39
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.10.0
  - mkl=2024.0
  - chromadb=0.5.3
  - intake-xarray
  - scikit-image
  - scikit-learn
  - pandas
  - pytest
  - python-dotenv
  - s3fs
  - jupyterlab
  - jupytext
  - pip
  - streamlit
  - plotly
  - pip:
    - scivision
    - git+https://github.com/alan-turing-institute/plankton-cefas-scivision@main
