name: cyto_39
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - s3fs
  - matplotlib
  - python-dotenv
  - dask
  - pip:
    - pytest
    - captum
    - imagecodecs
    - intake # for reading scivision
    - torch==1.10.0 # install before cefas_scivision; it needs this version
    - scivision
    - scikit-image
    - setuptools==69.5.1 # because this bug https://github.com/pytorch/serve/issues/3176
    - tiffile
    - git+https://github.com/alan-turing-institute/plankton-cefas-scivision@main # torch version
    - chromadb
