name: cyto_ml
channels:
  - pytorch
  - conda-forge
channel_priority: flexible
dependencies:
  - python=3.12
  - pytorch
  - black
  - chromadb
  - flake8
  - intake-xarray
  - intake=0.7
  - isort
  - jupyterlab
  - jupytext
  - matplotlib
  - pandas
  - pytest
  - python-dotenv
  - s3fs
  - scikit-image
  - xarray
  - pip
  - pip:
    - git+https://github.com/jmarshrossney/resnet50-cefas
