name: cyto_ml
channels:
  - pytorch
  - conda-forge
channel_priority: flexible
dependencies:
  - python=3.12
  - pytorch
  - black
  - boto3
  - aioboto3
  - chromadb
  - dvc[s3]
  - fastapi
  - flake8
  - isort
  - jupyterlab
  - jupytext
  - luigi
  - matplotlib
  - pandas
  - Pillow
  - pytest
  - pytest-mock
  - python-dotenv
  - scikit-learn
  - scikit-image
  - sqlalchemy==1.4.54 # see https://github.com/spotify/luigi/issues/3227
  - xarray
  - pip
  - streamlit
  - plotly
  - uvicorn
  - pip:
    - git+https://github.com/jmarshrossney/resnet50-cefas
