name: Graphviz re-render
on: 
  push:
    paths: 'docs/diagrams/**/*'

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: ts-graphviz/setup-graphviz@v2
    - name: Setup Graphviz
      run: |
        chmod +x ./scripts/render_diagrams.sh
        ./scripts/render_diagrams.sh
      shell: bash
    - name: Upload artifact
      # Automatically uploads docs directory, will this work?
      uses: actions/upload-pages-artifact@v1
      with:
        path: "docs/"