name: Graphviz re-render
on: 
  push:
    paths: 'docs/diagrams/**/*'

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: ts-graphviz/setup-graphviz@v2
    - name: Setup Graphviz
      run: |
        chmod +x ./scripts/render_diagrams.sh
        ./scripts/render_diagrams.sh
      shell: bash
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        cache-version: 0 # Increment this number if you need to re-download cached gems
        working-directory: '${{ github.workspace }}/docs'
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Build with Jekyll
      # Outputs to the './_site' directory by default
      # Will this copy the diagrams tho
      run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v4
      with:
        path: "docs/_site"