name: Pages and Graphviz re-render
on: 
  push:
    branches:
      - main
    paths: 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Rebuild graphs and pages 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt
        pip install -e .
    - name: Build docs
      run: |
        cd docs
        sphinx-apidoc -o source/api ../src
        make html
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'docs/_build/html'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2