on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  test-python:
    # "cannot specify version when calling local workflows"
    uses: ./.github/workflows/test_python.yml